### POST
POST http://localhost:5000/api/wilder/create HTTP/1.1
Content-Type: application/json

{
    "name":"Wilder",
    "city": "Londres",
    "skills":[
        {"title":"express", "votes":5},
        {"title":"mongo", "votes":12}
    ]
}

### GET
GET http://localhost:5000/api/wilder/read HTTP/1.1

### PUT
PUT http://localhost:5000/api/wilder/update
Content-Type: application/json

{
    "_id": "6076eddd38bdd032f5d4a21",
    "name":"update Wilder",
    "city": "update Londres",
    "skills":[
        {"title":"express", "votes":5},
        {"title":"mongo", "votes":12}
    ]
}

### DELETE
DELETE http://localhost:5000/api/wilder/delete
Content-Type: application/json

{"_id": "6076e179f9361d15e97c7287"}